### ISSUE TITLE
Popup width defaults to 100%

### ISSUE THREAD

**Issue by 381181295** [kaiyuyue/Windowed-Safari#2]
Safari: 18.1 (20619.2.8.11.10)
MacOS: 15.1
Windowed: 1.0.3

When clicking on the  `Full screen` button, the Windowed popup is displayed with a width of 100% (sometimes more, and the options are not even visible in the actual screen).

![cURSPEUW@2x](https://github.com/user-attachments/assets/524dd86b-12ed-41f3-b220-676d3aa194ed)

**Comment by kaiyuyue** [comment]
I also updated my MacOS this week and I have the same version as yours. But the extension still works well (on YouTube). Could you please disable the other video-based controlling extensions first, and try again? I guess it is affected by the other extensions.

**Comment by 381181295** [comment]
Ahh yeah, my bad. Just noticed SponsorBlock for YouTube is the extension causing the issue. Once i disabled that one the popup looks alright.

![repsEWzP@2x](https://github.com/user-attachments/assets/aea31c8a-0d3b-45cc-a510-40df861c34d2)
